FROM node:20.15.0-alpine3.20

WORKDIR /app

ARG DB_URL
ARG MAIL_SERVICE
ARG MAIL_USER
ARG MAIL_PASS

ENV PORT=3333
ENV SALT=12
ENV SECRET="secret"
ENV EXPIRY_TIME_SECONDS=3000

ENV DATABASE_URL=$DB_URL
ENV MAIL_SERVICE=$MAIL_SERVICE
ENV MAIL_USER=$MAIL_USER
ENV MAIL_PASS=$MAIL_PASS

COPY . .

RUN yarn install
RUN yarn build
RUN yarn prisma generate

EXPOSE 3333

CMD yarn prisma migrate deploy && yarn start
