import {
  loginPath,
  signUpPath,
  forgetPasswordPath,
  changePasswordPath,
  waitingCodePath,
  loadPetsPath,
  loadGuardianNamePath,
  loadCatBreedsPath,
  loadDogBreedsPath,
  loadCatSizesPath,
  loadDogSizesPath,
  petRegistryPath,
  updatePetPath,
  deletePetPath,
  emailConfirmationPath,
  createSchedulerPath,
  addTagPath,
  updateTagPath,
  loadTagByIdPath,
  deleteTagByIdPath,
  loadTagsPath,
  loadCurrentDateTasksPath,
  loadCurrentWeekTasksPath
} from './paths/'
import { loadCurrentMonthTasksPath } from './paths/tasks/load-current-month-tasks-path'

export default {
  '/signup': signUpPath,
  '/login': loginPath,
  '/forget-password': forgetPasswordPath,
  '/guardian/change-password': changePasswordPath,
  '/guardian/email-confirmation/{userId}': emailConfirmationPath,
  '/waiting-code': waitingCodePath,
  '/pet': { ...petRegistryPath, ...loadPetsPath },
  '/pet/{petId}': { ...updatePetPath, ...deletePetPath },
  '/guardian/name': loadGuardianNamePath,
  '/breeds/cat': loadCatBreedsPath,
  '/breeds/dog': loadDogBreedsPath,
  '/sizes/cat': loadCatSizesPath,
  '/sizes/dog': loadDogSizesPath,
  '/scheduler': createSchedulerPath,
  '/tag': { ...addTagPath, ...loadTagsPath },
  '/tag/{tagId}': { ...updateTagPath, ...loadTagByIdPath, ...deleteTagByIdPath },
  '/tasks/current-date': loadCurrentDateTasksPath,
  '/tasks/current-week': loadCurrentWeekTasksPath,
  '/tasks/current-month': loadCurrentMonthTasksPath
}
